### Ready probe
GET http://localhost:8800/ready

### Health probe
GET http://localhost:8800/health

### User by id
GET http://localhost:8800/user/1?fields=email,id

### swagger
GET http://localhost:8800/swagger/index.html